# Generated by Django 4.2 on 2023-04-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('address', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('Identical_Document_1_picture', models.ImageField(upload_to='images/donorID/')),
                ('Identical_Document_1_number', models.CharField(max_length=50)),
                ('Identical_Document_1_expiry_Date', models.CharField(max_length=10)),
                ('Identical_Document_2_picture', models.ImageField(blank=True, upload_to='images/donorID/')),
                ('Identical_Document_2_number', models.CharField(blank=True, max_length=50)),
                ('Identical_Document_2_expiry_Date', models.CharField(max_length=10)),
                ('Identical_Document_3_picture', models.ImageField(blank=True, upload_to='images/donorID/')),
                ('Identical_Document_3_number', models.CharField(blank=True, max_length=50)),
                ('Identical_Document_3_expiry_Date', models.CharField(max_length=10)),
                ('ABN', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
