# Generated by Django 4.2 on 2023-05-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('previousAddress', models.CharField(max_length=100)),
                ('familymembers', models.IntegerField(blank=True)),
                ('email', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('Identity_Document_1_picture', models.ImageField(upload_to='images/recipientID/')),
                ('Identity_Document_1_number', models.CharField(max_length=50)),
                ('Identity_Document_1_expiry_Date', models.CharField(max_length=10)),
                ('Identity_Document_2_picture', models.ImageField(blank=True, upload_to='images/recipientID/')),
                ('Identity_Document_2_number', models.CharField(blank=True, max_length=50)),
                ('Identity_Document_2_expiry_Date', models.CharField(blank=True, max_length=10)),
                ('Identity_Document_3_picture', models.ImageField(blank=True, upload_to='images/recipientID/')),
                ('Identity_Document_3_number', models.CharField(blank=True, max_length=50)),
                ('Identity_Document_3_expiry_Date', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
