# Generated by Django 4.2 on 2023-05-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_donorinformation_identical_document_2_expiry_date_and_more'),
        ('app', '0002_recipientinformation'),
    ]

    operations = [
    ]
