# Generated by Django 4.2 on 2023-05-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_merge_20230502_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AidKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kitName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AidItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=50)),
                ('itemQuantity', models.IntegerField()),
                ('itemUnit', models.CharField(max_length=10)),
                ('itemBaselineQuantity', models.IntegerField()),
                ('foodBrandName', models.CharField(blank=True, max_length=50, null=True)),
                ('foodExpiryDate', models.DateField(blank=True, null=True)),
                ('mainIngredients', models.TextField(blank=True, null=True)),
                ('allergenInformation', models.TextField(blank=True, null=True)),
                ('clothingSizeInformation', models.CharField(blank=True, max_length=10, null=True)),
                ('itemCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aidcategory')),
                ('itemKit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aidkit')),
            ],
        ),
    ]
