# Generated by Django 4.2 on 2023-05-03 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyModel',
            new_name='Page',
        ),
    ]
