# Generated by Django 4.2 on 2023-05-07 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_mymodel_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipientFamilymember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('relationship', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True)),
                ('Identity_Document_1_picture', models.ImageField(upload_to='images/recipientID/')),
                ('Identity_Document_1_number', models.CharField(max_length=50)),
                ('Identity_Document_1_expiry_Date', models.CharField(max_length=10)),
                ('Identity_Document_2_picture', models.ImageField(blank=True, upload_to='images/recipientID/')),
                ('Identity_Document_2_number', models.CharField(blank=True, max_length=50)),
                ('Identity_Document_2_expiry_Date', models.CharField(blank=True, max_length=10)),
                ('Identity_Document_3_picture', models.ImageField(blank=True, upload_to='images/recipientID/')),
                ('Identity_Document_3_number', models.CharField(blank=True, max_length=50)),
                ('Identity_Document_3_expiry_Date', models.CharField(blank=True, max_length=10)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recipientinformation')),
            ],
        ),
        migrations.AddField(
            model_name='recipientinformation',
            name='family_members',
            field=models.ManyToManyField(to='app.recipientfamilymember'),
        ),
    ]
