# Generated by Django 4.2 on 2023-05-08 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_aidcategory_aidkit_aiditem'),
        ('app', '0007_recipientfamilymember_and_more'),
    ]

    operations = [
    ]
