# Generated by Django 4.2 on 2023-05-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_merge_20230508_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipientinformation',
            name='family_members',
        ),
        migrations.AlterField(
            model_name='aiditem',
            name='itemCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
        migrations.DeleteModel(
            name='AidCategory',
        ),
    ]
