# Generated by Django 4.2 on 2023-05-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_recipientinformation_family_members_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateReceived', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('donatedItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aiditem')),
                ('donationDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.donation')),
            ],
        ),
    ]
