# Generated by Django 4.2 on 2023-05-09 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_aidkit_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='AidItemRequest',
            fields=[
                ('requestId', models.AutoField(primary_key=True, serialize=False)),
                ('requestFulfilled', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='recipientfamilymember',
            name='Identity_Document_2_expiry_Date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipientfamilymember',
            name='Identity_Document_2_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipientfamilymember',
            name='Identity_Document_2_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipientID/'),
        ),
        migrations.AlterField(
            model_name='recipientfamilymember',
            name='Identity_Document_3_expiry_Date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipientfamilymember',
            name='Identity_Document_3_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipientfamilymember',
            name='Identity_Document_3_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipientID/'),
        ),
        migrations.AlterField(
            model_name='recipientfamilymember',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipientinformation',
            name='Identity_Document_2_expiry_Date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipientinformation',
            name='Identity_Document_2_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipientinformation',
            name='Identity_Document_3_expiry_Date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipientinformation',
            name='Identity_Document_3_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='recipientinformation',
            name='Identity_Document_3_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/recipientID/'),
        ),
        migrations.AlterField(
            model_name='recipientinformation',
            name='familymembers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aiditem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.aiditemrequest')),
            ],
        ),
        migrations.AddField(
            model_name='aiditemrequest',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.recipientinformation'),
        ),
    ]
