# Generated by Django 4.2 on 2023-05-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_aiditemrequest_notes_donorinformation_hq_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientinformation',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
